name: 'Sentry release'
description: 'An action which creates a sentry release on a github release creation.'
inputs:
  release:
    description: 'Name of a release. Usually a git tag'
    required: true
runs:
  using: 'node12'
  main: 'dist/index.js'
